networks:
  public: null

services:
  demo-frontend:
    image: node:lts
    working_dir: /opt/source
    entrypoint: "/opt/entrypoint.dev.sh"
    volumes:
      - ./services/frontend/source:/opt/source
      - ./services/frontend/entrypoint.dev.sh:/opt/entrypoint.dev.sh
    ports:
      - 7030:5173 # vite dev server
      - 7031:9000 # node debugger
      - 7032:9001 # node debugger test
      - 7033:4000 # vitest ui server

  demo-backend:
    image: node:lts
    entrypoint: "/opt/entrypoint.dev.sh"
    working_dir: /opt/source
    volumes:
      - ./services/backend/source:/opt/source
      - ./services/backend/entrypoint.dev.sh:/opt/entrypoint.dev.sh
    ports:
      - 7010:3000 # backend server
      - 7011:9000 # node debugger
      - 7012:9001 # node debugger test
      - 7013:4000 # vitest ui server

  demo-db:
    ports:
      - "7020:${DB_PORT}"
