networks:
  public: null

services:
  demo-frontend:
    build:
      context: ./services/frontend
      dockerfile: Dockerfile.prod
      args:
        VITE_HOST_ENV: ${FRONTEND_VITE_HOST_ENV}
    image: demo-frontend
    working_dir: /opt/source
    ports:
      - 7030:80 # serve server

  demo-backend:
    build:
      context: ./services/backend
      dockerfile: Dockerfile.prod
    image: demo-backend
    working_dir: /opt/source
    ports:
      - 7010:3000 # backend server
